on:
  push

jobs:
  ubuntu:
    name: Build for ubuntu
    runs-on: ubuntu-latest
    container: earthcomputer/java-and-rust:1.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: libjava-native-file-chooser.so
          path: ./target/release/libjava-native-file-chooser.so
  windows:
    name: Build for windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          CPATH: ${{ env.JAVA_HOME }}\include;${{ env.JAVA_HOME }}\include\win32
      - uses: actions/upload-artifact@v3
        with:
          name: java-native-file-chooser.dll
          path: .\target\release\java-native-file-chooser.dll
